=== OpenNMS/opennms/opennms-config/src/main/castor/translator-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://xmlns.opennms.org/xsd/translator-configuration"
	xmlns:this="http://xmlns.opennms.org/xsd/translator-configuration"
	elementFormDefault="qualified">

		<element name="value">
			<annotation>
				<documentation>
					An element representing a value to be used in a
					translation. 
				</documentation>
			</annotation>
			<complexType>
 				<sequence>
					<element ref="this:value" minOccurs="0" maxOccurs="unbounded"/>
				</sequence>
				<attribute name="result" type="string" use="required" />
				<attribute name="matches" type="string" use="optional" />
				<attribute name="type" type="string" use="required" />
				<attribute name="name" type="string" use="optional" />
			</complexType>

		</element>
		
		<element name="assignment">
			<annotation>
				<documentation>
					An element representing an assignement to an attribute of the event
				</documentation>
			</annotation>
			<complexType>
				<sequence>
					<element ref="this:value" minOccurs="1" maxOccurs="1"/>
				</sequence>
				<attribute name="type" type="string" use="required" />
				<attribute name="name" type="string" use="required" />
			</complexType>
		</element>

	<!--  elements defining this xsd -->
	<element name="event-translator-configuration">
		<complexType>
			<sequence>
				<element ref="this:translation" minOccurs="0"
					maxOccurs="1" />
			</sequence>
		</complexType>
	</element>
	<element name="translation">
		<annotation>
			<documentation>
				List of OpenNMS events for which the Event Translator 
				will subscribe for translation.
			</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="this:event-translation-spec" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<element name="event-translation-spec">
		<annotation>
			<documentation>
				This defines the allowable translations for a given
				event uei
			</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="this:mappings" minOccurs="1"
					maxOccurs="1" />
			</sequence>
			<attribute name="uei" type="string" use="required" />
		</complexType>
	</element>
	<element name="mappings">
		<annotation>
			<documentation>
				The list of event mappings for this event. The first
				mapping that matches the event is used to translate the
				event into a new event.
			</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="this:mapping" minOccurs="0"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<element name="mapping">
		<annotation>
			<documentation>
				A mapping for a given event. This translation is only
				applied if it is the first that matches
			</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="this:assignment" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
</schema>

=== OpenNMS/opennms/opennms-container/delta-v/eventtranslator-overlay/etc/translator-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<event-translator-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xmlns.opennms.org/xsd/translator-configuration http://www.opennms.org/xsd/config/translator-configuration.xsd ">
  
  <!-- Improved LinkDown/LinkUp events.  Uses translator to add DB information to link status traps events -->
  <translation>
    <event-translation-spec uei="uei.opennms.org/generic/traps/SNMP_Link_Down">
      <mappings>
        <mapping>
          <assignment name="uei" type="field" >
            <value type="constant" result="uei.opennms.org/translator/traps/SNMP_Link_Down" />
          </assignment>
          <assignment name="ifDescr" type="parameter" default="Unknown">
            <value type="sql" result="SELECT snmp.snmpIfDescr FROM snmpInterface snmp WHERE snmp.nodeid = ?::integer AND snmp.snmpifindex = ?::integer" >
              <value type="field" name="nodeid" matches=".*" result="${0}" />
              <value type="parameter" name="~^\.1\.3\.6\.1\.2\.1\.2\.2\.1\.1\.([0-9]*)$" matches=".*" result="${0}" />
            </value>
          </assignment>
          <assignment name="ifName" type="parameter" default="Unknown">
            <value type="sql" result="SELECT snmp.snmpIfName FROM snmpInterface snmp WHERE snmp.nodeid = ?::integer AND snmp.snmpifindex = ?::integer" >
              <value type="field" name="nodeid" matches=".*" result="${0}" />
              <value type="parameter" name="~^\.1\.3\.6\.1\.2\.1\.2\.2\.1\.1\.([0-9]*)$" matches=".*" result="${0}" />
            </value>
          </assignment>
          <assignment name="ifAlias" type="parameter" default="Unknown">
            <value type="sql" result="SELECT snmp.snmpIfAlias FROM snmpInterface snmp WHERE snmp.nodeid = ?::integer AND snmp.snmpifindex = ?::integer" >
              <value type="field" name="nodeid" matches=".*" result="${0}" />
              <value type="parameter" name="~^\.1\.3\.6\.1\.2\.1\.2\.2\.1\.1\.([0-9]*)$" matches=".*" result="${0}" />
            </value>
          </assignment>
        </mapping>
        <mapping>
          <assignment name="uei" type="field" >
            <value type="constant" result="uei.opennms.org/internal/topology/linkDown" />
          </assignment>
        </mapping>
      </mappings>
    </event-translation-spec>
    <event-translation-spec uei="uei.opennms.org/generic/traps/SNMP_Link_Up">
      <mappings>
        <mapping>
          <assignment name="uei" type="field" >
            <value type="constant" result="uei.opennms.org/translator/traps/SNMP_Link_Up" />
          </assignment>
          <assignment name="ifDescr" type="parameter" default="Unknown">
            <value type="sql" result="SELECT snmp.snmpIfDescr FROM snmpInterface snmp WHERE snmp.nodeid = ?::integer AND snmp.snmpifindex = ?::integer" >
              <value type="field" name="nodeid" matches=".*" result="${0}" />
              <value type="parameter" name="~^\.1\.3\.6\.1\.2\.1\.2\.2\.1\.1\.([0-9]*)$" matches=".*" result="${0}" />
            </value>
          </assignment>
          <assignment name="ifName" type="parameter" default="Unknown">
            <value type="sql" result="SELECT snmp.snmpIfName FROM snmpInterface snmp WHERE snmp.nodeid = ?::integer AND snmp.snmpifindex = ?::integer" >
              <value type="field" name="nodeid" matches=".*" result="${0}" />
              <value type="parameter" name="~^\.1\.3\.6\.1\.2\.1\.2\.2\.1\.1\.([0-9]*)$" matches=".*" result="${0}" />
            </value>
          </assignment>
          <assignment name="ifAlias" type="parameter" default="Unknown">
            <value type="sql" result="SELECT snmp.snmpIfAlias FROM snmpInterface snmp WHERE snmp.nodeid = ?::integer AND snmp.snmpifindex = ?::integer" >
              <value type="field" name="nodeid" matches=".*" result="${0}" />
              <value type="parameter" name="~^\.1\.3\.6\.1\.2\.1\.2\.2\.1\.1\.([0-9]*)$" matches=".*" result="${0}" />
            </value>
          </assignment>
        </mapping>
        <mapping>
          <assignment name="uei" type="field" >
            <value type="constant" result="uei.opennms.org/internal/topology/linkUp" />
          </assignment>
        </mapping>
      </mappings>
    </event-translation-spec>
    
    <!-- Translations for configuration management -->
    <event-translation-spec uei="uei.opennms.org/vendor/Cisco/traps/ciscoConfigManEvent" >
      <mappings>
        <mapping>
          <assignment name="uei" type="field" >
            <value type="constant" result="uei.opennms.org/internal/translator/entityConfigChanged" />
          </assignment>
          <assignment name="configSource" type="parameter" >
            <!-- ccmHistoryEventCommandSource -->
            <value type="parameter" name="~^\.1\.3\.6\.1\.4\.1\.9\.9\.43\.1\.1\.6\.1\.3\..*" matches=".*" result="${0}" />
          </assignment>
          <assignment name="configUser" type="parameter" >
            <value type="constant" result="Unknown" />
          </assignment>
        </mapping>
      </mappings>
    </event-translation-spec>
    <event-translation-spec uei="uei.opennms.org/vendor/Juniper/traps/jnxCmCfgChange" >
      <mappings>
        <mapping>
          <assignment name="uei" type="field" >
            <value type="constant" result="uei.opennms.org/internal/translator/entityConfigChanged" />
          </assignment>
          <assignment name="configSource" type="parameter" >
            <value type="parameter" name="~^\.1\.3\.6\.1\.4\.1\.2636\.3\.18\.1\.7\.1\.4\..*" matches=".*" result="${0}" />
          </assignment>
          <assignment name="configUser" type="parameter" >
            <value type="parameter" name="~^\.1\.3\.6\.1\.4\.1\.2636\.3\.18\.1\.7\.1\.5\..*" matches=".*" result="${0}" />
          </assignment>
        </mapping>
      </mappings>
    </event-translation-spec>

    <!-- Translations for clock skew detection -->
    <event-translation-spec uei="uei.opennms.org/internal/telemetry/clockSkewDetected" >
      <mappings>
        <mapping>
          <assignment name="uei" type="field" >
            <value type="constant" result="uei.opennms.org/translator/telemetry/clockSkewDetected" />
          </assignment>
          <assignment name="nodeid" type="field" >
            <value type="sql" result="SELECT n.nodeid FROM node n, ipinterface i WHERE n.nodeid = i.nodeid AND i.ipaddr = ? AND n.location = ?" >
              <value type="field" name="interface"  matches=".*" result="${0}" />
              <value type="parameter" name="monitoringSystemLocation" matches=".*" result="${0}" />
            </value>
          </assignment>
        </mapping>
      </mappings>
    </event-translation-spec>

    <!-- Cloud service status → passiveServiceStatus translations.
         Syslog messages matching CLOUD-STATUS produce cloud/serviceDown or cloud/serviceUp
         events. These are translated into passiveServiceStatus events consumed by
         PassiveStatusKeeper, which drives PassiveServiceMonitor on Minion. -->
    <event-translation-spec uei="uei.opennms.org/syslogd/cloud/serviceDown">
      <mappings>
        <mapping>
          <assignment name="uei" type="field">
            <value type="constant" result="uei.opennms.org/services/passiveServiceStatus"/>
          </assignment>
          <assignment name="passiveNodeLabel" type="parameter">
            <value type="sql" result="SELECT nodelabel FROM node WHERE nodeid = ?::integer">
              <value type="field" name="nodeid" matches=".*" result="${0}"/>
            </value>
          </assignment>
          <assignment name="passiveIpAddr" type="parameter">
            <value type="field" name="interface" matches=".*" result="${0}"/>
          </assignment>
          <assignment name="passiveServiceName" type="parameter">
            <value type="parameter" name="cloudService" matches=".*" result="${0}"/>
          </assignment>
          <assignment name="passiveStatus" type="parameter">
            <value type="constant" result="Down"/>
          </assignment>
        </mapping>
      </mappings>
    </event-translation-spec>

    <event-translation-spec uei="uei.opennms.org/syslogd/cloud/serviceUp">
      <mappings>
        <mapping>
          <assignment name="uei" type="field">
            <value type="constant" result="uei.opennms.org/services/passiveServiceStatus"/>
          </assignment>
          <assignment name="passiveNodeLabel" type="parameter">
            <value type="sql" result="SELECT nodelabel FROM node WHERE nodeid = ?::integer">
              <value type="field" name="nodeid" matches=".*" result="${0}"/>
            </value>
          </assignment>
          <assignment name="passiveIpAddr" type="parameter">
            <value type="field" name="interface" matches=".*" result="${0}"/>
          </assignment>
          <assignment name="passiveServiceName" type="parameter">
            <value type="parameter" name="cloudService" matches=".*" result="${0}"/>
          </assignment>
          <assignment name="passiveStatus" type="parameter">
            <value type="constant" result="Up"/>
          </assignment>
        </mapping>
      </mappings>
    </event-translation-spec>

  </translation>

</event-translator-configuration>
